spring:
  profiles: local, test
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: honeybadger
    password: dontcare
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          show_sql: true
server:
  port: 8082
