eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.url:http://localhost:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:test}
    nonSecurePort: 80
encryption:
  key: test123456781234
  iv: 87b7225d16ea2ae1f41d0b13fdce9bba

---
spring:
  profiles: local
  security:
    user:
      password: welcome1
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9001/oauth/check_token
    client:
      client-id: configserver
      client-secret: configserversecret
server:
  port: 9000
eureka:
  client:
    register-with-eureka: false