eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.url:http://localhost:8761/eureka/}
    register-with-eureka: false
  instance:
    hostname: ${vcap.application.uris[0]:test}
    nonSecurePort: 80
encryption:
  key: test123456781234
  iv: 87b7225d16ea2ae1f41d0b13fdce9bba

server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.unreleased.work/auth/realms/oauth2-test/protocol/openid-connect/certs


logging:
  level:
    root: DEBUG

---
spring:
  profiles: local
  security:
    user:
      password: welcome1

server:
  port: 9000
eureka:
  client:
    register-with-eureka: false